modLoader="javafml" #mandatory
loaderVersion="[28,)" #mandatory (28 is current forge version)

[[mods]] #mandatory
modId="omniheads" #mandatory
version="0.1" #mandatory
displayName="OmniHeads" #mandatory
authors="Omnisentient" #optional
description='''
Adds custom heads as blocks instead of entities
'''
[[dependencies.omniheads]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[28,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.omniheads]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"
