modLoader="javafml"
loaderVersion="[28,)"

[[mods]]
modId="omniheads"
version="1.13"
displayName="OmniHeads"
authors="Omnisentient"
description='''
Adds head-like blocks to reduce tile entity count
Adds almost 100 unique blocks not counting the color variations
'''