modLoader="javafml"
loaderVersion="[28,)"

[[mods]]
modId="omniheads"
version="1.12.2"
displayName="OmniHeads"
authors="Omnisentient"
description='''
Adds head-like blocks to reduce tile entity count
Adds almost 100 unique blocks, with count of color variation not included
'''